# Generated by Django 3.2.5 on 2021-09-21 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию из предложенных.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='money.category'),
        ),
    ]
