# Generated by Django 3.2.5 on 2021-09-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_expense_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию из предложенных.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='money.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
    ]
